baseURL = "http://streaaam.org/"
languageCode = "en-us"
title = "Streaaam"
theme = "hello-friend-ng"

[params]
	# Subtitle
	homeSubtitle = "A community created streaming site"

	# Show links to other posts
	disableReadOtherPosts = false	

[languages]
  [languages.en]
    title = "Streaaam"
    subtitle = "A community-run streaming site"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Streaaam"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "artists"
    name       = "Artists"
    url        = "/artists"

  [[menu.main]]
    identifier = "faq"
    name       = "FAQ"
    url        = "/faq"

  [[menu.main]]
    identifier = "schedule"
    name       = "Schedule"
    url        = "/schedule"

  [[menu.main]]
    identifier = "about-us"
    name       = "About Us"
    url        = "/about-us"


